In [35]:
import numpy as np

array = np.arange(1,10+1)
print("Array = ",array)

multiplicando = np.multiply(array, 5)
print("Multi = ",multiplicando)

somando = np.sum(array * 3, axis=0)
print("Soman = ",somando)

fatiando = array[3:6]
print("Fatia = ", fatiando)

fatiaZero = fatiando - fatiando
print("Fzero = ", fatiaZero)

Array =  [ 1  2  3  4  5  6  7  8  9 10]
Multi =  [ 5 10 15 20 25 30 35 40 45 50]
Soman =  165
Fatia =  [4 5 6]
Fzero =  [0 0 0]


In [21]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arrayZeros = np.zeros((4,5))
print("array",arrayZeros)
arrayZeros.dtype

array [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


dtype('float64')

In [30]:
arrayOnes = np.ones((5,3), dtype=np.int32)
print("array",arrayOnes)
arrayOnes.dtype

array [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int32')